apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-world
  creationTimestamp: null
  labels:
    app: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world
    spec:
      containers:
      - image: ghcr.io/gbrawl/node-hello-world@sha256:5cd5c5b3a8c9106b7cbd57457a75edd1a4dc978a7c4dfae487a12526973b624f
        name: hello-world
        resources: {}
        imagePullPolicy: Always
status: {}
