apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: hello-world
spec:
  rules:
  - host: hello-world.apps.openshift.bvb.local
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: web
---
